"""
Verified mapping between CloudFormation service prefixes and IAM Authorization Reference service names.

This eliminates false positives from substring matching (e.g., "ec2" matching "ec2fleet").
The mapping is manually curated and should be updated when AWS adds new services.
"""

CFN_TO_IAM_SERVICE = {
    "ec2": "Amazon EC2",
    "s3": "Amazon S3",
    "s3objectlambda": "Amazon S3 Object Lambda",
    "s3outposts": "Amazon S3 on Outposts",
    "lambda": "AWS Lambda",
    "iam": "AWS Identity and Access Management",
    "cloudformation": "AWS CloudFormation",
    "dynamodb": "Amazon DynamoDB",
    "rds": "Amazon RDS",
    "ecs": "Amazon Elastic Container Service",
    "ecr": "Amazon Elastic Container Registry",
    "eks": "Amazon Elastic Kubernetes Service",
    "sns": "Amazon SNS",
    "sqs": "Amazon SQS",
    "apigateway": "Amazon API Gateway Management",
    "apigatewayv2": "Amazon API Gateway Management V2",
    "cloudwatch": "Amazon CloudWatch",
    "logs": "Amazon CloudWatch Logs",
    "events": "Amazon EventBridge",
    "cognito": "Amazon Cognito Identity",
    "kms": "AWS Key Management Service",
    "secretsmanager": "AWS Secrets Manager",
    "ssm": "AWS Systems Manager",
    "stepfunctions": "AWS Step Functions",
    "glue": "AWS Glue",
    "athena": "Amazon Athena",
    "kinesis": "Amazon Kinesis",
    "kinesisfirehose": "Amazon Kinesis Firehose",
    "kinesisanalytics": "Amazon Kinesis Analytics",
    "kinesisanalyticsv2": "Amazon Kinesis Analytics V2",
    "elasticache": "Amazon ElastiCache",
    "elasticsearch": "Amazon OpenSearch Service",
    "opensearchservice": "Amazon OpenSearch Service",
    "redshift": "Amazon Redshift",
    "emr": "Amazon EMR",
    "sagemaker": "Amazon SageMaker",
    "codebuild": "AWS CodeBuild",
    "codepipeline": "AWS CodePipeline",
    "codedeploy": "AWS CodeDeploy",
    "codecommit": "AWS CodeCommit",
    "route53": "Amazon Route 53",
    "route53resolver": "Amazon Route 53 Resolver",
    "cloudfront": "Amazon CloudFront",
    "waf": "AWS WAF",
    "wafv2": "AWS WAF V2",
    "wafregional": "AWS WAF Regional",
    "guardduty": "Amazon GuardDuty",
    "config": "AWS Config",
    "cloudtrail": "AWS CloudTrail",
    "certificatemanager": "AWS Certificate Manager",
    "directconnect": "AWS Direct Connect",
    "networkfirewall": "AWS Network Firewall",
    "backup": "AWS Backup",
    "transfer": "AWS Transfer Family",
    "appsync": "AWS AppSync",
    "amplify": "AWS Amplify",
    "iot": "AWS IoT",
    "iotanalytics": "AWS IoT Analytics",
    "iotevents": "AWS IoT Events",
    "iotsitewise": "AWS IoT SiteWise",
    "iottwinmaker": "AWS IoT TwinMaker",
    "mediaconvert": "AWS Elemental MediaConvert",
    "medialive": "AWS Elemental MediaLive",
    "mediapackage": "AWS Elemental MediaPackage",
    "mediastore": "AWS Elemental MediaStore",
    "gamelift": "Amazon GameLift",
    "appstream": "Amazon AppStream 2.0",
    "workspaces": "Amazon WorkSpaces",
    "connect": "Amazon Connect",
    "lex": "Amazon Lex",
    "pinpoint": "Amazon Pinpoint",
    "ses": "Amazon SES",
    "batch": "AWS Batch",
    "datasync": "AWS DataSync",
    "fsx": "Amazon FSx",
    "efs": "Amazon Elastic File System",
    "lakeformation": "AWS Lake Formation",
    "ram": "AWS Resource Access Manager",
    "servicecatalog": "AWS Service Catalog",
    "organizations": "AWS Organizations",
    "sso": "AWS IAM Identity Center",
    "inspector": "Amazon Inspector",
    "inspectorv2": "Amazon Inspector2",
    "macie": "Amazon Macie",
    "securityhub": "AWS Security Hub",
    "detective": "Amazon Detective",
    "networkmanager": "AWS Network Manager",
    "applicationautoscaling": "Application Auto Scaling",
    "autoscaling": "Amazon EC2 Auto Scaling",
    "elasticloadbalancing": "Elastic Load Balancing",
    "elasticloadbalancingv2": "Elastic Load Balancing V2",
    "lightsail": "Amazon Lightsail",
    "docdb": "Amazon DocumentDB",
    "neptune": "Amazon Neptune",
    "qldb": "Amazon QLDB",
    "timestream": "Amazon Timestream",
    "msk": "Amazon Managed Streaming for Apache Kafka",
    "amazonmq": "Amazon MQ",
    "eventschemas": "Amazon EventBridge Schemas",
    "appconfig": "AWS AppConfig",
    "chatbot": "AWS Chatbot",
    "groundstation": "AWS Ground Station",
    "robomaker": "AWS RoboMaker",
    "greengrass": "AWS IoT Greengrass",
    "greengrassv2": "AWS IoT Greengrass V2",
    "location": "Amazon Location Service",
    "healthlake": "Amazon HealthLake",
    "comprehend": "Amazon Comprehend",
    "textract": "Amazon Textract",
    "translate": "Amazon Translate",
    "transcribe": "Amazon Transcribe",
    "polly": "Amazon Polly",
    "rekognition": "Amazon Rekognition",
    "personalize": "Amazon Personalize",
    "forecast": "Amazon Forecast",
    "kendra": "Amazon Kendra",
    "codeartifact": "AWS CodeArtifact",
    "proton": "AWS Proton",
    "apprunner": "AWS App Runner",
    "memorydb": "Amazon MemoryDB for Redis",
    "grafana": "Amazon Managed Grafana",
    "aps": "Amazon Managed Service for Prometheus",
    "finspace": "Amazon FinSpace",
    "mwaa": "Amazon Managed Workflows for Apache Airflow",
    "devopsguru": "Amazon DevOps Guru",
    "lookoutequipment": "Amazon Lookout for Equipment",
    "lookoutmetrics": "Amazon Lookout for Metrics",
    "lookoutvision": "Amazon Lookout for Vision",
    "nimblestudio": "Amazon Nimble Studio",
    "panorama": "AWS Panorama",
    "resiliencehub": "AWS Resilience Hub",
    "wisdom": "Amazon Connect Wisdom",
    "voiceid": "Amazon Connect Voice ID",
    "controltower": "AWS Control Tower",
    "auditmanager": "AWS Audit Manager",
    "fis": "AWS Fault Injection Simulator",
    "billingconductor": "AWS Billing Conductor",
    "m2": "AWS Mainframe Modernization",
    "redshiftserverless": "Amazon Redshift Serverless",
    "scheduler": "Amazon EventBridge Scheduler",
    "pipes": "Amazon EventBridge Pipes",
    "cleanrooms": "AWS Clean Rooms",
    "omics": "Amazon Omics",
    "simspaceweaver": "AWS SimSpace Weaver",
    "securitylake": "Amazon Security Lake",
    "vpclattice": "Amazon VPC Lattice",
    "internetmonitor": "Amazon CloudWatch Internet Monitor",
    "bedrock": "Amazon Bedrock",
    "codeconnections": "AWS CodeConnections",
    "entityresolution": "AWS Entity Resolution",
    "b2bi": "AWS B2B Data Interchange",
    "bcmdataexports": "AWS Billing and Cost Management Data Exports",
    "qbusiness": "Amazon Q Business",
    "launchwizard": "AWS Launch Wizard",
    "deadline": "AWS Deadline Cloud",
    "pcaconnectorad": "AWS Private CA Connector for Active Directory",
    "pcaconnectorscep": "AWS Private CA Connector for SCEP",
    "socialmessaging": "AWS End User Messaging Social",
}


def get_iam_service_name(cfn_prefix: str) -> str | None:
    """Get the IAM Authorization Reference service name for a CFN prefix."""
    return CFN_TO_IAM_SERVICE.get(cfn_prefix.lower())


def normalize_for_fuzzy_match(name: str) -> str:
    """Normalize a service name for fuzzy matching as fallback."""
    return (
        name.lower()
        .replace(" ", "")
        .replace("-", "")
        .replace("_", "")
        .replace("amazon", "")
        .replace("aws", "")
    )
